---
title: "CV"
author: "Natalie Jones"
date: "9/17/2021"
output:
  html_document:
    df_print: paged
---

## Name: Natalie Jones

## Department Address
* 110 North Hall 1050 Bascom Mall University of Wisconsin-Madison Madison, WI 53706

## Email Address 
* nljones3@wisc.edu

## Website
* https://polisci.wisc.edu

## Education 
* University of Wisconsin Madison
* Iowa State University
* Arrowhead High School

## Research experience
* Research Assistant 2019-August 2020 Iowa State University
* Fellowship in Political Science at University of St.Louis
* Society of Political Methodology Undergraduate Initiative
* ICPSR Summer 2020
 

## Teaching experience
* Tutoring experience


## Conference presentations
* Emerging Scholars 2020

## Awards and fellowships
* University of Wisconsin Fellow Political Science
## Fellowship in Political Science at University of St.Louis
* Fellowship in Political Science atIowa State University 
* SHEA Native Scholarship
* Dean's High Impact Award for Undergraduate Research Iowa State University 2020
* Cobell Indian Undergraduate Award  2017,2018,2019,2020
*Dean's High Impact Award for Undergraduate Research Iowa State University 2020
* Whitaker-Lindgren Scholars in Political Science 2019, 2020
* John and Eleanore I. McKinley Scholarship Delta Zeta 2020
* Liberal Arts and Sciences Excellence Scholarship 2018 2019,2020
* Elizabeth Coulter Stephenson Grant recipient 2020
* Kedrowski and Fitzgerald Family Legacy of Heroines 2020
* Phi Beta Kappa Honors Society member

## Service/volunteer work
* Delta Zeta Sorority Member/ Philanthopist 
* Big Brothers Big Sisters of Central Iowa acadmic Voluntter

## Professional work experience 
* NSF Funded Fellowships

## Language and skills
* English


## References
* Dave Peterson, Iowa State University Professor.
* Zach Bonner, Iowa State University Professor. 


---